settings:
  title: 'woojinkim.org Status Page'
  url: 'https://status.woojinkim.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: woojinkim-org
    name: woojinkim.org
    url: 'https://woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: docs-woojinkim-org
    name: docs.woojinkim.org
    url: 'https://docs.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: mastodon-woojinkim-org
    name: mastodon.woojinkim.org
    url: 'https://mastodon.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: mail-woojinkim-org
    name: mail.woojinkim.org
    url: 'http://mail.woojinkim.org/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: blog-woojinkim-org
    name: blog.woojinkim.org
    url: 'https://blog.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: playground-woojinkim-org
    name: playground.woojinkim.org
    url: 'https://playground.woojinkim.org'
    method: GET
    expectStatus: 403
    followRedirect: true
    linkable: true

  - id: status-woojinkim-org
    name: status.woojinkim.org
    url: 'https://status.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: cf-status-woojinkim-org
    name: cf-status.woojinkim.org
    url: 'https://cf-status.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: neoocean-net
    name: neoocean.net
    url: 'https://neoocean.net'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: status-neoocean-net
    name: status.neoocean.net
    url: 'https://status.neoocean.net'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: kono-pub
    name: kono.pub
    url: 'https://kono.pub'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: docs-kono-pub
    name: docs.kono.pub
    url: 'https://docs.kono.pub'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: todo-kono-pub
    name: todo.kono.pub
    url: 'https://todo.kono.pub'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: status-kono-pub
    name: status.kono.pub
    url: 'https://status.kono.pub'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
