settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: kono-pub # unique identifier
    name: kono.pub
    url: 'https://kono.pub'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: mastodon-woojinkim-org
    name: mastodon.woojinkim.org
    url: 'https://mastodon.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: woojinkim-org
    name: woojinkim.org
    url: 'https://woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: mail-woojinkim-org
    name: mail.woojinkim.org
    url: 'mail.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: sengi-woojinkim-org
    name: sengi.woojinkim.org
    url: 'sengi.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: blog-woojinkim.org
    name: blog.woojinkim.org
    url: 'blog.woojinkim.org'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true